### ISSUE TITLE
Removing timer.cpp in newer VST3 SDK releases breaks linux build

### ISSUE THREAD

**Issue by mtytel** [free-audio/clap-wrapper#266] opened 2024-07-05 14:41 UTC
If you use a newer (3.7.9) or later vst3 sdk, then the removal of timer.cpp actually breaks the build.
It worked for me when I left timer.cpp included with the newer vst3 sdk builds.

https://github.com/free-audio/clap-wrapper/blob/497f40a7580a2f6326fa06691f39aa3d7e0e78a7/cmake/base_sdks.cmake#L137

**Comment by baconpaul** [comment] 2024-07-05 15:55
Sigh. OK I wonder if there is a cmake-time way to check the version. The problem is timer.cpp throws a bunch of warnings and errors in older SDKs.

**Comment by mtytel** [comment] 2024-07-05 17:07
https://github.com/free-audio/clap-wrapper/pull/269

**Comment by defiantnerd** [comment] 2024-07-05 18:42
this looks good for me.

**Comment by baconpaul** [comment] 2024-07-05 20:24
yup all merged. Thanks matt!

**Closed** 2024-07-05 20:24 UTC
